#!/bin/bash

# -n NUM: read returns after reading num characters rather than waiting for a complete line of input.
# -p PROMPT: display PROMPT, without a trailing newline, before attempting to read any input. The prompt is displayed only if input is coming from a terminal.
# -r: If this option is given, backslash does not act as an escape character. The backslash is considered to be part of the line. In particular, a backslash-newline pair may not be used as a line continuation.
read -p "Are you in the project? (y/n) " -n 1 -r

echo

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    # if no
    read -p "Folder name ($package_name): " folder_name

    dir=${folder_name//[^a-zA-Z0-9]/-}

    cd $dir
fi

echo

composer require laravel-frontend-presets/tailwindcss

read -p "Do you want to install preset with auth(y/n)" -n 1 -r

echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    #if no
    php artisan preset tailwindcss
else
    php artisan preset tailwindcss-auth
fi

echo

npm install && npm run dev

